const SET_TOKEN = 'RESET_TOKEN';
const SET_ID = 'SET_ID';
const SET_PW = 'SET_PW';
const SET_EMAIL = 'SET_EMAIL';

const GET_USER = 'GET_USER';
const GET_TOKEN = 'GET_TOKEN';
const GET_ID = 'GET_ID';
const GET_EMAIL = 'GET_EMAIL';

const LOGIN = 'LOGIN';
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

export default {
    SET_EMAIL,
    SET_ID,
    SET_PW,
    SET_EMAIL,
    SET_TOKEN,
    GET_USER,
    GET_EMAIL,
    GET_ID,
    GET_TOKEN,
    LOGIN,
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILURE
}